// Utility functions for exporting transcripts (TXT and PDF)

/**
 * Generates a unique ID for filenames
 * @param prefix Optional prefix for the ID
 * @returns A string with the format prefix-YYYYMMDD-HHMMSS-XXX where XXX is a random 3-digit number
 */
export function generateUniqueId(prefix: string = "transcript"): string {
  const now = new Date();

  const date =
    now.getFullYear().toString() +
    (now.getMonth() + 1).toString().padStart(2, "0") +
    now.getDate().toString().padStart(2, "0");

  const time =
    now.getHours().toString().padStart(2, "0") +
    now.getMinutes().toString().padStart(2, "0") +
    now.getSeconds().toString().padStart(2, "0");

  const random = Math.floor(Math.random() * 1000)
    .toString()
    .padStart(3, "0");

  return `${prefix}-${date}-${time}-${random}`;
}

/**
 * Formats a transcript for download as a text file
 * @param transcript Array of transcript items
 * @param title Optional title to include at the top of the file
 * @returns Formatted string ready for download
 */
export function formatTranscriptForDownload(
  transcript: Array<{ text: string; duration?: number; offset?: number }>,
  title?: string
): string {
  const timestamp = new Date().toLocaleString();
  let content = "";

  content += "Transcript Generated for Free by youtranscripts.com\n";
  content += "==========================================================\n\n";

  if (title) {
    content += `Title: ${title}\n`;
    content += "=".repeat(title.length + 7) + "\n\n";
  }

  content += `Generated on: ${timestamp}\n\n`;

  transcript.forEach((item, index) => {
    content += item.text + "\n";
    if ((index + 1) % 5 === 0) {
      content += "\n";
    }
  });

  content += "\n\n==========================================================\n";
  content += "Generated by youtranscripts.com - Free YouTube Transcript Tool\n";

  return content;
}

import { jsPDF } from "jspdf";

/**
 * Generates and downloads a PDF file containing only the transcript text
 */
export function downloadAsPdf(content: string, filename: string): void {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxLineWidth = pageWidth - margin * 2;
  // Split text into lines fitting page width
  const lines = doc.splitTextToSize(content, maxLineWidth);
  // Paginate text manually to support multi-page transcripts
  const pageHeight = doc.internal.pageSize.getHeight();
  const fontSize = doc.getFontSize();
  const lineHeight = fontSize * 1.2;
  let y = margin;
  lines.forEach((line: string) => {
    if (y + lineHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  });
  const outputName = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  doc.save(outputName);
}

/**
 * Downloads content as a file
 * @param content The text content to download
 * @param filename The name of the file without extension
 * @param format The format of the file (txt or pdf)
 */
export function downloadTextFile(
  content: string,
  filename: string,
  format: "txt" | "pdf" = "txt"
): void {
  if (format === "pdf") {
    downloadAsPdf(content, filename);
    return;
  }

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".txt") ? filename : `${filename}.txt`;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}
