"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, HelpCircle } from "lucide-react";

type FaqItem = {
  question: string;
  answer: string;
};

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqItems: FaqItem[] = [
    {
      question: "What is a YouTube transcript?",
      answer:
        "A YouTube transcript is the full text of everything spoken in a video, generated by YouTube's caption engine or a third-party tool. It lets you read, search and repurpose your video content as text.",
    },
    {
      question: "How do I generate a YouTube transcript for any video?",
      answer:
        "Just paste your YouTube video URL into YouTranscripts (youtranscripts.com), click Generate Transcript, and get the complete text in seconds—no manual typing needed.",
    },
    {
      question: "Is YouTube transcript generation free to use?",
      answer:
        "Yes—our YouTube transcript tool is 100% free. You can generate and download unlimited transcripts without signup, fees, or hidden charges.",
    },
    {
      question:
        "How do I download YouTube video transcripts in TXT, DOC, PDF or SRT format?",
      answer:
        "After generating your transcript on youtranscripts.com, click Download and choose TXT, DOC, PDF or SRT. Your YouTube video transcript will save instantly in the format you need.",
    },
    {
      question: "Can I translate YouTube transcripts to other languages?",
      answer:
        "Absolutely. Click Translate Transcript, select any target language, and our tool will deliver an accurate, translated YouTube transcript ready for reading or export.",
    },
    {
      question:
        "Is there a limit to video length or number of transcripts I can generate?",
      answer:
        "Nope—there's no maximum video length or usage cap. YouTranscripts handles videos of any duration and lets you create as many transcripts as you like.",
    },
    {
      question:
        "How accurate are the transcripts generated by YouTube video transcript generator by YouTranscripts?",
      answer:
        "Accuracy depends on audio quality and speaker clarity. On clear, well-recorded videos, you'll see ~90%+ accuracy. And you can always edit any remaining errors before exporting.",
    },
    {
      question:
        "Do I need to create an account to extract YouTube transcripts?",
      answer:
        "Not at all. No login or account is required—just paste the URL and start transcribing immediately.",
    },
  ];

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      className="w-full py-16 md:py-20 bg-[#f5f5f5] dark:bg-gray-900"
      id="faq"
    >
      <div className="w-[90%] mx-auto">
        <div className="flex flex-col items-center text-center mb-10">
          <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-4 max-w-4xl">
            Frequently Asked Questions
          </h2>
          <p className="max-w-[800px] text-lg mb-10">
            Everything you need to know about using YouTranscripts to generate
            YouTube video transcripts.
          </p>
        </div>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqItems.map((item, index) => (
            <div
              key={index}
              className="border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 rounded-lg overflow-hidden shadow-sm"
            >
              <button
                className="flex justify-between items-center w-full p-4 text-left bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                onClick={() => toggleFaq(index)}
              >
                <h3 className="text-lg font-medium">{item.question}</h3>
                {openIndex === index ? (
                  <ChevronUp className="h-5 w-5 flex-shrink-0" />
                ) : (
                  <ChevronDown className="h-5 w-5 flex-shrink-0" />
                )}
              </button>
              {openIndex === index && (
                <div className="p-4 bg-gray-50 dark:bg-gray-700/50 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-gray-700 dark:text-gray-300">
                    {item.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="flex justify-center mt-12">
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              // Scroll to the top of the page (hero section)
              window.scrollTo({ top: 0, behavior: "smooth" });
            }}
            className="bg-black hover:bg-gray-800 text-white font-bold py-3 px-8 rounded-lg transition-colors cursor-pointer"
          >
            Try YouTube Transcript Generator for free
          </a>
        </div>
      </div>
    </section>
  );
}
