"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, HelpCircle } from "lucide-react";

type FaqItem = {
  question: string;
  answer: string;
};

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqItems: FaqItem[] = [
    {
      question: "Is YouTubeTranscriptTool free to use?",
      answer:
        "Yes, YouTubeTranscriptTool is completely free to use. You can easily extract subtitles/transcripts generated by YouTube from YouTube videos without any cost.",
    },
    {
      question: "How do I access the transcript after generating it?",
      answer:
        "After clicking 'Get Transcript', the transcript will be displayed on the page. You can copy it, translate it, or use our AI tools to process it further.",
    },
    {
      question: "Can I translate the transcript to other languages?",
      answer:
        "Yes, you can translate the transcript to over 125 languages. Simply click the 'Translate' button after generating the transcript and select your desired language.",
    },
    {
      question: "Is there a limit to the length of the video I can transcribe?",
      answer:
        "There is no specific limit, but very long videos (over several hours) might take longer to process. The tool works best with videos that have subtitles or captions already available on YouTube.",
    },
    {
      question: "How long does it take to generate the transcript?",
      answer:
        "The transcript is usually generated within seconds, depending on the length of the video and your internet connection speed.",
    },
    {
      question: "Can I download the transcript?",
      answer:
        "Yes, you can copy the transcript and save it to your device as a text file or any other format you prefer.",
    },
  ];

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="w-full py-12 bg-background" id="faq">
      <div className="w-[90%] mx-auto">
        <div className="flex justify-center mb-8">
          <div className="bg-green-500 text-white rounded-full p-4">
            <HelpCircle className="h-8 w-8" />
          </div>
        </div>
        <h2 className="text-3xl font-bold text-center mb-12">FAQ</h2>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqItems.map((item, index) => (
            <div
              key={index}
              className="border border-border rounded-lg overflow-hidden"
            >
              <button
                className="flex justify-between items-center w-full p-4 text-left bg-background hover:bg-muted/50 transition-colors"
                onClick={() => toggleFaq(index)}
              >
                <h3 className="text-lg font-medium">{item.question}</h3>
                {openIndex === index ? (
                  <ChevronUp className="h-5 w-5 flex-shrink-0" />
                ) : (
                  <ChevronDown className="h-5 w-5 flex-shrink-0" />
                )}
              </button>
              {openIndex === index && (
                <div className="p-4 bg-muted/30 border-t border-border">
                  <p className="text-foreground/80">{item.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="flex justify-center mt-12">
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              // Scroll to the top of the page (hero section)
              window.scrollTo({ top: 0, behavior: "smooth" });
            }}
            className="bg-gray-800 hover:bg-gray-700 text-white font-bold py-3 px-8 rounded-lg transition-colors cursor-pointer"
          >
            Try YouTube Transcript Generator for free
          </a>
        </div>
      </div>
    </section>
  );
}
